spring:
  profile:
    active: local
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres

jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: validate
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: '8081'

currency-api:
  url: 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange'